version: "3"
services:
  nginx:
    build: infra/nginx
    container_name: nginx
    ports:
      - 41000:41000
      - 42000:42000
  php:
    build: infra/php
    container_name: php
    tty: true
    ports:
      - 30000:30000
      - 30001:30001
    volumes:
      - ./src:/var/src
    environment:
      - BOOTSTRAP=/var/src/bootstraps/bootstrap.php
  redis:
    build: infra/redis
    container_name: redis
