version: "3"
services:
  php:
    build: infra/php
    container_name: php
    tty: true
    volumes:
      - ./src:/var/src
    ports:
      - 30000:30000
      - 30001:30001
  redis:
    build: infra/redis
    container_name: redis
